// GLOBAL CONSTANTS
// -----------------------------------

export const APP_COLORS = {
    'primary':                '#5d9cec',
    'success':                '#27c24c',
    'info':                   '#23b7e5',
    'warning':                '#ff902b',
    'danger':                 '#f05050',
    'inverse':                '#131e26',
    'green':                  '#37bc9b',
    'pink':                   '#f532e5',
    'purple':                 '#7266ba',
    'dark':                   '#3a3f51',
    'yellow':                 '#fad732',
    'gray-darker':            '#232735',
    'gray-dark':              '#3a3f51',
    'gray':                   '#dde6e9',
    'gray-light':             '#e4eaec',
    'gray-lighter':           '#edf1f2'
};

export const APP_MEDIAQUERY = {
    'desktopLG':             1200,
    'desktop':                992,
    'tablet':                 768,
    'mobile':                 480
};

export const BadgeStatus = {
         Approaching: "badge-info",
         Contacted: "badge-info",
         Engaged: "badge-success",
         New: "badge-info",
         Error: "badge-danger",
         "Error syncing": "badge-danger",
         "Error in the sequencer": "badge-danger",
         "ROE violation Error": "badge-danger",
         Bounced: "badge-danger",
         Referral: "badge-danger",
         "Appointment booked": "badge-success",
         "Opportunity created": "badge-success",
         "Waiting to import": "badge-info",
         Importing: "badge-primary",
         "Import Complete": "badge-success",
         "Import Partial Complete": "badge-warning",
         Paused: "badge-warning",
         "Error Importing": "badge-danger",
       };

export const Industries = ["Software", "Media", " Media", "Public Relations", "Computer Software", "IT Services", "Services", "Social Media", "Information Technology & Services", "Marketing & Advertising", "Retail", "(Holding company)", "Software & Services", "Internet Software & Services", "Internet", "Travel & Tourism", "Advertising / Marketing", "-1", "Independent Power and Renewable Electricity Producers", "Renewable Electricity", "Renewable Energy", "Commercial Services & Supplies", "Chemicals", "Holding Companies", "Professional Services", "Chemicals, Petrochemicals, Glass & Gases", "eCommerce", "Aerospace & Defense", "Retailing", "Consumer Staples", "Consumer Discretionary", "Food Processing", "Consumer Products", "Consumer Goods", "Automobiles & Components", "Automotive", "Logistics / Transportation", "Telecom / Communication Services", "Logistics and Supply Chain", "Transportation/Trucking/Railroad", "Information Technology and Services", "Industrial Automation", "Media & Internet", "Real Estate / Property Management", "Commercial & Professional Services", "Consulting", "Financial Services", "Venture Capital & Private Equity", "Management Consulting", "Law Practice", "4G V-Station", "4G Fingervein Station", "3D Face", "Consumer Electronics", "Defense & Space", "Public Safety", "B2B", "Computer Hardware", "Computer Peripherals", "3D Printers", "Enterprise", "3D Printing", "Architecture & Engineering", "Technology", "Hotels, Restaurants & Leisure", "Health & Wellness", "Marketplace", "Publishing", "Marketing and Advertising", "B2C", "Mechanical Engineering", "Printing", "Business Supplies and Equipment", "Electrical", "Mechanical or Industrial Engineering", "Corporate & Business", "Architecture", "Business Supplies", "Mobile", "Plastics", "Design", "Medicine", "Medical Devices", "Entertainment", "Arts and Crafts", "Products Fixed line and mobile telephony", "Internet services", "3G", "Telecommunications", "4Projects", "Venture Capital", "8D Company Building Program", "Engine manufacturing", "AMG GT", "AMG GT S", "AML8726-MX", "Semiconductors", "Interactive entertainment", "www.GamersFirst.com", "APB Reloaded", "Computer Games", "Community Manager", "Lifecycle Manager", "API Gateway", "Civil Engineering", "Plug & Protect", "ASAPer", "Business Services", "Aakash tablet", "Ubislate 7", "PocketSurfer", "Accessori e moda", "Speciality Retail", "Apparel", "Accessories", "Cosmetics", "Department Stores", "Education Management", "Wine and Spirits", "Kids Apparel", "Homeware.", "Consumer Durables & Apparel", "Textiles, Apparel & Luxury Goods", "Apparel, Accessories & Luxury Goods", "Jewellery", "Clothing", "Shoes", "Commerce de détail", "Online Media", "Accessories and Perfumes", "Insurance", "Property and Casualty", "Accident and Health", "Life insurance", "Diversified Financials", "Diversified Financial Services", "Accounting", "Diversified Consumer Services", "Education Services", "Education", "Higher Education", "Accounting Services", "Consumer Services", "Lodging", "Apparel & Fashion", "Manufacturing - Durables", "Industrial Machinery & Equipment", "Manufacturing", "Executive Office", "Consulting & Professional Services", "Technology Hardware & Equipment", "Communications Equipment", "Computer Networking", "Materials", "Wholesale", "Human Resources", "Hospitals / Health Care", "Food & Beverages", "Hospitality", "Energy Equipment & Services", "Gas Utilities", "Oil & Gas", "Capital Goods", "Construction & Engineering", "Energy / Utilities", "SAAS", "Supermarkets", "Building Products", "Defense & Aerospace", "Building Materials", "Electrical & Electronic Manufacturing", "Marketing", "Health Care Equipment & Services", "Health Care Providers & Services", "Health Care", "Hospital & Health Care", "Health, Wellness and Fitness", "Health, Wellness & Fitness", "Computer & Network Security", "Pharmaceuticals, Biotechnology & Life Sciences", "Biotechnology", "Advertising", "Manufacturing - Non-Durables", "IT", "Logistics & Supply Chain", "E-commerce", "Accounting & Accounting Services", "Staffing & Recruiting", "Finance", "Legal Services", "Real Estate", "Entertainment & Recreation", "Events", "Capital Markets", "Banking", "Investment Management", "Investment Banking", "Household Durables", "Software Development & Design", "E-learning", "Market Research", "Distributors", "Food, Beverage & Tobacco", "Food Products", "Agricultural Products", "Beverages", "Internet & Catalog Retail", "Technology Hardware, Storage & Peripherals", "Specialized Consumer Services", "Security & Investigations", "Public Relations and Communications", "Food, Beverages & Tobacco", "Electrical Equipment", "Non-Profit", "Pharmaceuticals", "Leisure", "Brokerage", "Information Services", "Aviation & Aerospace", "Oil & Energy", "Banks", "Family Services", "Photography", "Construction", "Online Publishing", "Restaurants", "Print & Digital Media", "Human Resources & Staffing", "Architecture & Planning", "Staffing and Recruiting", "Pet Products", "School Districts", "Professional Training & Coaching", "Nonprofit Organization Management", "Machinery", "Grocery Retail", "Human Resource & Employment Services", "Outsourcing/Offshoring", "Mining & Metals", "Plumbing & HVAC Equipment", "ISP", "Home & Furniture", "Leisure Products", "Sporting Goods", "Healthcare General", "Transportation", "Air Freight & Logistics", "Shipping & Logistics", "Facilities Services", "Non-Profit & Philanthropy", "Packaging and Containers", "Health Insurance", "Credit Cards & Transaction Processing", "Commercial & Residential Construction", "Religion", "Airlines", "State", "Networking", "Wireless", "Healthcare", "Utilities", "Research", "Sports", "Broadcasting", "Construction Contractors & Services", "Banking & Mortgages", "Energy", "Music", "Travel & Leisure", "Government", "Apparel & Footwear", "Warehousing", "Environmental Services", "Business Supplies & Equipment", "Gas Stations, Convenience & Liquor Stores", "Investment Banking & Brokerage", "Fundraising", "Textiles", "Waste Management", "Energy, Utilities & Waste Treatment", "Outsourcing", "Technologies et services de l’information", "Society", "Commercial Printing", "Investment", "Industrials & Manufacturing", "Comptabilité", "Food Production", "Recruiting", "Alternative Medicine", "Metals & Mining", "Events Services", "Security", "Payments", "Media Production", "Commercial Real Estate", "Assurance services",
 "Tax advisory", "advisory services", "Pulp & Paper", "Broadcast Media", "Federal", "Philanthropy", "Government Administration", "Agriculture & Forestry", "Office Products Retail & Distribution", "Facilities Management & Commercial Cleaning", "Graphic Design", "Writing & Editing", "Medical Practice", "Motor Vehicle Dealers", "Finance General", "Marknadsföring och reklam", "Recreation", "Consumer Finance", "Software & Technical Consulting", "Debt Collection", "Contabilidad", "Professional Training", "Accounting software", "Business Intelligence", "Electronic Document Management", "Accounts Receivable Management", "Customer Relationship Management", "Back Office Solutions", "Action figures", "Controls and Actuators design and manufacturing", "Controls", "Actuators", "Programmatic Ad Buying", "Ad-Tech", "Adaptive Optics", "MEMS", "Customized MEMS products and standardized Deformable mirrors", "Nanotechnology", "Administration publique", "Administration scolaire et universitaire", "Catalysts", "Adsorbents", "Process technology", "yellow-pages", "media-company", "Newspapers", "Diversified Telecommunication Services", "Communications", "Commodity Chemicals", "Telecommunication Services", "Integrated Telecommunication Services", "High Performance Computing", "Big Data Analytics and Petascale Storage solutions", "Electricity, Oil & Gas", "Call Centers & Business Centers", "Movies & Entertainment", "Data Mining", "Animation", "Information Collection & Delivery", "Video", "Emerging Markets", "Mobile Advertising", "Internet Marketing", "Big Data", "Startups", "Casinos & Gambling", "Research & Consulting Services", "International Relations", "Public Policy", "Leisure, Travel & Tourism", "Fund-Raising", "Freight & Logistics Services", "Construction General", "Airlines/Aviation", "Advertising & Marketing & Digital", "Program Development", "Security Products & Services", "Gaming Software/Systems", "Diversified Capital Markets", "Hospitality General", "Cloud Services", "Writing and Editing", "Renewables & Environment", "Arts", "Power Conversion & Protection Equipment", "Electronics", "Search Engines & Internet Portals", "International Trade & Development", "Health Care Equipment & Supplies", "BPO & service transformation", "Back office administration", "Customer service", "Life Sciences Tools & Services", "Advertising technology", "Social marketing technology", "SRAX and GroupAd", "Motion Pictures and Film", "apps", "app-downloads", "app-marketing", "Casinos & Gaming", "Telephony & Wireless", "Food", "Newspapers & News Services", "Web Services & Apps", "Fine Art", "Containers & Packaging", "Construction Materials", "Marine", "Religious Organizations", "Manufacturing General", "Music & Music Related Services", "Multimedia & Graphic Design", "Film/Video Production & Services", "E-Commerce & Marketplaces", "International Trade and Development", "Test & Measurement Equipment", "Lodging & Resorts", "Education General", "Law Enforcement", "Outsourcing Services", "Subcontrataciones/Offshoring", "Mental Health Care", "Print Media", "Security and Investigations", "Government Relations", "Translation and Localization", "Motion Pictures & Film", "Life Sciences", "Primary/Secondary Education", "Training", "International Affairs", "Packaging & Containers", "Political Organization", "Gambling & Casinos", "Local", "Wine & Spirits", "Think Tanks", "Marketing et publicité", "Civic & Social Organization", "Libraries", "Waste Treatment, Environmental Services & Recycling", "Luxury Goods & Jewelry", "Paper & Forest Products", "Personal Computers & Peripherals", "Retail General", "Miscellaneous Building Materials (Flooring, Cabinets, etc.)", "Furniture", "Automotive Manufacturing", "Communities", "Advice", "Parenting", "Advocacy", "Defense", "Aerospace", "Nuclear power", "Electric Utilities", "Military", "Agriculture", "Photography Platforms", "Flight Controllers", "Trading Companies & Distributors", "Airlines, Airports & Air Services", "Leisure & Travel", "Turboshaft and jet engines", "Scientific Instruments", "Minerals & Mining", "pci", "serdes", "mpeg", "Industrial Conglomerates", "Individual & Family Services", "Electronic Components", "Boats & Submarines", "Photographic & Optical Equipment", "Défense et espace", "Metals & Minerals", "Mining", "Olja och energi", "Skeppsbyggnad", "Affaires étrangères", "Aggregates, Concrete & Cement", "Agricultural Biologicals / Biostimulants", "Ranching", "Home Improvement", "Dairy", "Crops", "Farming", "Chimie", "Animals & Livestock",
 "Packaged Foods & Meats", "Agriculture General", "Real Estate Investment Trusts", "Automation", "Lumber, Wood Production & Timber Operations", "Household Goods", "Paper Products", "Import & Export", "Agro-alimentaire", "Package/Freight Delivery", "Logiciels informatiques", "Auctions", "Logistics", "International Trade", "Supply Chain and Logistics", "Automotive Service & Collision Repair", "Maritime", "Aircraft maintenance", "Car & Truck Rental", "Compagnie aérienne/Aviation", "Oil, Gas & Consumable Fuels", "Medical Device", "Import and Export", "Computer and video games", "The Lord of the Rings Online", "Dungeons & Dragons Online", "Travel Agencies & Services", "Resources", "Airports", "Alarm services for business customers and consumers", "Kuvan", "Naglazyme", "Aldurazyme", "Pure Alpha", "All Weather", "Pure Alpha Major Markets", "Alprolix", "Avonex", "Eloctate", "Alternative Dispute Resolution", "Tobacco", "Fund of Funds", "Asset Management", "Alternative Investment Management", "Law Firms & Legal Services", "Translation", "Health and Wellness", "Sports & Fitness", "Scientific & Academic Research", "Health Care Services", "American cuisine", "Tex-Mex cuisine", "Ammunition", "missile and propulsion systems", "Amusement Parks, Arcades & Attractions", "Big Data Analytics", "Analytics", "Cloud Data Services", "Social Bookmarking", "Dhingana for iphone", "Android", "BlackBerry", "television series", "motion pictures", "Justin Time", "Recreational Facilities and Services", "Video games", "Anläggningstjänster", "Annata IDMS", "Whole and Universal Life", "Annuities", "and Disability Insurance", "Anti-piracy", "online piracy tracking", "Offices", "Apartments", "Shopping Malls", "App Stores", "Marketplaces", "Sports equipment", "Boating shoes", "Racquets", "Footwear", "Apparel & Accessories Retail", "Housewares", "Jewelry, Watches & Luxury Goods", "Textiles & Apparel", "Toys & Games", "Shirts", "Shorts", "Sweaters", "Performing Arts", "Cosmetics, Beauty Supply & Personal Care Products", "Department Stores, Shopping Centers & Superstores", "Household Products", "Professional Sports", "Real Estate Management & Development", "retail store", "Household & Personal Products", "Personal Products", "Fashion accessories", "News", "Talent Agencies", "Eyewear", "Paper Goods", "Drug Manufacturing & Research", "Arts & Crafts", "Shipbuilding", "Hair Salons", "Cosmétiques", "Industrie textile", "Confection et mode", "Transportation General", "Pets", "Veterinary", "Toys", "Chipsets", "motherboards", "CPUs", "Swimwear", "Detaljhandel", "Hardware", "Multiline Retail", "Apparel & Home", "Specialty Retail", "Homefurnishing Retail", "Womenswear", "Perfume", "Jewelery", "Articles de luxe et bijouterie", "Personalwesen", "Museums and Institutions", "Flowers, Gifts & Specialty Stores", "Articles de sport", "Appliances", "SoCs", "Application Processor", "Application lifecycle management", "Palamida Enterprise Edition 6", "Application performance management", "Frooti", "Appy", "LMN", "Online and computer-based examinations", "Aptech Computer Education", "Arena Animation", "Aqueous Hybrid Ion (AHI) battery", "Planning", "Contractors", "Construction Management", "Architecture, Engineering & Design", "Loisirs, voyages et tourisme", "Motor Vehicle Parts", "Semiconductor & Semiconductor Equipment", "Telecommunications General", "Plastic, Packaging & Containers", "Business Services General", "Wire & Cable", "Medical Devices & Equipment", "Riskkapital", "Engineering", "Hôtellerie et hébergement", "Architecture et urbanisme", "Arkitektur och planering", "Art Gallery", "Curated Web", "Museums", "Legislative Office", "Musées et institutions culturelles", "Production audiovisuelle", "Films d’animation", "Leisure Facilities", "Investment products", "Arts et artisanat", "Asigra Cloud Backup", "Banques", "Services financiers", "Asset Management & Custody Banks", "Wealth management", "Private banking", "Associations et organisations sociales et syndicales", "Assurances", "Funpark Friends", "Car Jack Streets", "Astro Ranch", "Atego Asset Library", "Atego Process Director", "Atego ApexAda Developer", "Atendimento ao consumidor", "Audience measurement", "Audio", "Audiobooks", "Auto Components", "Electronic Equipment, Instruments & Components", "Railroad Manufacture", "Automatismes industriels", "Automobile Parts Stores", "Automobile financing", "Automobiles", "engines", "commercial vehicles", "Motor Vehicles", "Glass, Ceramics & Concrete", "Trucks", "Military vehicles", "Road & Rail", "Personal och rekrytering", "Företagsrådgivning", "Emballages et conteneurs", "Fishery", "Video games (casual games)", "Plastiques", "Ground Transportation", "Industrial", "Computer Equipment & Peripherals", "Facilities", "Conseil en management", "Médias en ligne", "distribution and marketing", "Chrysler", "Dodge", "Jeep", "Trax", "Traveller", "Trump", "Automotive sales and services", "Consumer credit", "Consumer engineering", "VTRUX Suv", "VTRUX Van", "Metals", "Cars", "Automotive Bearings", "Industrial Bearings", "Railways Bearings", "peer-to-peer", "Automotive industry", "Automotive systems", "Home Improvement & Hardware Retail", "Aviation and aerospace insurance and reinsurance", "casualty insurance and reinsurance", "energy insurance", "Avocats", "Aéronautique et aérospatiale", "Broadband", "General aviation and military aircraft", "Brands:", "Beechcraft", "Computers", "hotels", "paperboards & specialty papers", "Natural Gas", "Firearms", "Charitable Organizations & Foundations", "Quality and luxury goods", "Television Stations", "Investment Banking/Venture", "Information & Document Management", "Gold", "Valuation", "Transaction Consulting", "Real Estate Advisory", "freelance"]

export const Titles =  ["CEO", "President", "Chief Financial Officer", "Consultant", "Account Executive", "Software Engineer", "Marketing Manager", "Owner", "Founder", "Vice President", "Director", "Project Manager", "Intern", "Account Manager", "Product Manager", "Controller", "CFO", "Managing Director", "Chief Executive Officer", "Board Member", "Partner", "Associate", "Manager", "Co-Founder", "Director of Marketing", "Principal", "General Manager", "Senior Software Engineer", "Business Development Manager", "Sales Manager", "Senior Consultant", "Chief Operating Officer", "Marketing Director", "Advisor", "CTO", "Chief Technology Officer", "Marketing Intern", "Marketing Coordinator", "Director of Sales", "Founder & CEO", "Software Developer", "Analyst", "Senior Account Executive", "Operations Manager", "Senior Product Manager", "Business Analyst", "Human Resources Manager", "Regional Sales Manager", "Executive Assistant", "Senior Vice President", "Chief Marketing Officer", "Research Assistant", "Director, Information Technology", "Executive Director", "Sales Associate", "Program Manager", "Senior Manager", "President & CEO", "Director of Operations", "Sales Representative", "Managing Partner", "Recruiter", "Financial Analyst", "Accounting Manager", "COO", "Creative Director", "Director of Finance", "Director of Human Resources", "Business Development", "Account Director", "Administrative Assistant", "HR Manager", "Sales Director", "Founder and CEO", "Director of Business Development", "Senior Associate", "Web Developer", "Office Manager", "Sales", "Executive Vice President", "IT Manager", "Senior Accountant", "Product Marketing Manager", "Senior Account Manager", "President and CEO", "Director, Human Resources", "Marketing Assistant", "Co-founder", "Finance Manager", "Systems Engineer", "Investor", "Vice President, Finance", "Advisory Board Member", "Vice President of Sales", "Digital Marketing Manager", "Marketing Consultant", "Graphic Designer", "Senior Marketing Manager", "VP", "Marketing Specialist", "CIO", "President & Chief Executive Officer", "Technical Recruiter", "Senior Project Manager", "Corporate Controller", "Assistant Controller", "Co Founder", "Chief Information Officer", "Account Supervisor", "Director, Finance", "Art Director", "Assistant Manager", "Developer", "Member", "Sales Executive", "President, CEO", "Staff Accountant", "Brand Manager", "Senior Analyst", "Accountant", "Board of Directors", "Director, Marketing", "Senior Financial Analyst", "Director of Engineering", "Chairman", "Vice President of Marketing", "Director of Product Management", "Principal Consultant", "Adjunct Professor", "Producer", "Engineer", "Director, Product Management", "VP Marketing", "Finance Director", "Marketing Associate", "Branch Manager", "Mentor", "Summer Intern", "Designer", "Systems Administrator", "IT Director", "Management Consultant", "VP Sales", "Marketing", "Engineering Manager", "Student", "Store Manager", "Public Relations Intern", "District Manager", "Director, Business Development", "Customer Service Representative", "HR Generalist", "Manager, Human Resources", "Programmer", "Instructor", "Research Associate", "Sr. Software Engineer", "Regional Sales Director", "President/CEO", "Vice President, Marketing", "CEO & Founder", "Summer Associate", "Associate Director", "Account Coordinator", "System Administrator", "Regional Manager", "Teaching Assistant", "Network Engineer", "VP Finance", "Vice President, Sales", "Sales Engineer", "Solutions Architect", "Social Media Manager", "Vice President, Information Technology", "Business Manager", "HR Director", "EA", "Marketing Communications Manager", "Director of Sales and Marketing", "Human Resources Generalist", "Independent Consultant", "Systems Analyst", "Audit Manager", "Production Manager", "Vice President, Human Resources", "Sr. Product Manager", "Director, Sales", "Network Administrator", "Software Architect", "Vice President of Operations", "Senior Developer", "Human Resources Director", "Senior Recruiter", "Attorney", "National Sales Manager", "Member Board of Directors", "IT Consultant", "Co-Founder & CEO", "VP Engineering", "National Account Manager", "Director of Information Technology", "VP Business Development", "Marketing Analyst", "Senior Software Developer", "Research Analyst", "Financial Controller", "Volunteer", "Project Coordinator", "Editor", "Sales Consultant", "Sales Development Representative", "Senior Auditor", "SVP", "District Sales Manager", "Vice President of Finance", "Senior Director", "Human Resources", "Project Engineer", "Senior Engineer", "Assistant Vice President", "Senior Business Analyst", "Teacher", "Vice President, Operations", "Internship", "Purchasing Manager", "Buyer", "Chief Revenue Officer", "Production Assistant", "Development Manager", "Head of Marketing", "VP of Marketing", "Data Analyst", "Recruiting Manager", "Technical Director", "Researcher", "VP of Sales", "Vice President Sales", "Senior Systems Engineer", "Director of Technology", "Supervisor", "Principal Software Engineer", "Marketing Executive", "Programmer Analyst", "Online Marketing Manager", "HR Business Partner", "CEO and Founder", "Solution Architect", "CMO", "Regional Vice President", "Architect", "Assistant Account Executive", "Executive Producer", "Engagement Manager", "Founder, CEO", "Auditor", "Financial Advisor", "Copywriter", "Manager, Accounting", "Regional Director", "Technical Lead", "Board Director", "Community Manager", "Key Account Manager", "Business Development Director", "Vice President, Business Development", "Team Leader", "Sr. Account Executive", "Server", "Director, Operations", "Vice President Human Resources", "Research Intern", "Director of Development", "Business Development Executive", "Associate Consultant", "Founder/CEO", "Territory Manager", "Board Observer", "Communications Manager", "Member of the Board of Directors", "Director of IT", "Business Consultant", "Program Director", "Team Lead", "Reporter", "Inside Sales Representative", "Treasurer", "Director of Communications", "Freelance Writer", "Author", "Writer", "Vice President Marketing", "Founding Partner", "Technical Consultant", "Principal Engineer", "Customer Success Manager", "VP of Engineering", "Sales Assistant", "Data Scientist", "Lead Software Engineer", "Senior Designer", "General Counsel", "Corporate Recruiter", "Adjunct Faculty", "CEO & Co-Founder", "Digital Marketing Specialist", "Associate Product Manager", "Web Designer", "Summer Analyst", "Recruitment Consultant", "Co-Founder and CEO", "Chief Product Officer", "Lead Developer", "Investment Banking Analyst", "VP Operations", "Director of Product Marketing", "Director Human Resources", "Senior Product Marketing Manager", "Office Assistant", "Software Development Manager", "Realtor", "Senior Program Manager", "Tax Manager", "Event Coordinator", "Director of Sales & Marketing", "Customer Service Manager", "Brand Ambassador", "Vice President of Human Resources", "Sr. Project Manager", "Lecturer", "Sr. Consultant", "Various", "Chairman of the Board", "Contractor", "Recruiting Coordinator", "Associate Creative Director", "Receptionist", "Project Leader", "Management Trainee", "Chief Architect", "HR Consultant", "Contributing Writer", "Editorial Intern", "Associate Marketing Manager", "Co-Owner", "Senior Technical Recruiter", "Managing Editor", "Media Planner", "Software Engineering Intern", "EVP", "IT Project Manager", "Director of HR", "Vice President, Product Management", "Sr. Financial Analyst", "Vice President of Business Development", "Director Business Development", "Area Sales Manager", "Chief Strategy Officer", "Design Engineer", "Human Resource Manager", "Project Director", "Area Manager", "Graduate Research Assistant", "Executive Recruiter", "Associate Producer", "Member of Technical Staff", "System Engineer", "Plant Manager", "Event Manager", "Chief Operations Officer", "Enterprise Account Executive", "Digital Marketing Consultant", "Business Development Representative", "VP of Operations", "Founder and President", "Director, Accounting", "Managing Consultant", "Vice President Finance", "VP of Finance", "Sales Operations Manager", "Senior Sales Executive", "Director Product Management", "Strategic Account Manager", "Senior VP", "Vice President Business Development", "Associate Brand Manager", "Enterprise Architect", "Assistant", "Member, Board of Directors", "Law Clerk", "Sr. Marketing Manager", "Audit Senior", "Fellow", "Senior Brand Manager", "Technical Architect", "Property Manager", "Software Consultant", "Senior Advisor", "Member Board Of Directors", "Human Resources Coordinator", "Business Owner", "Director, Product Development", "Product Development Manager", "Vice President of Engineering", "Human Resources Business Partner", "Chief Information Security Officer", "VP Sales and Marketing", "Research Scientist", "Technical Manager", "Founder & President", "Sales and Marketing Manager", "Human Resources Assistant", "HR Coordinator", "Director of Product Development", "Application Developer", "Member of the Board", "Contributor", "Sr. Recruiter", "Adjunct Instructor", "Trainee", "Sr. Technical Recruiter", "Territory Sales Manager", "Chief Human Resources Officer", "Non Executive Director", "Director, Product Marketing", "Client Services Manager", "Relationship Manager", "Contract Recruiter", "Director of Client Services", "Human Resources Intern", "Graduate Assistant", "Vice President of Sales and Marketing", "Product Specialist", "Talent Acquisition Manager", "Senior Network Engineer", "Webmaster", "Project Lead", "Cofounder", "Senior Sales Manager", "Sales Coordinator", "Technical Project Manager", "Sr. Account Manager", "Legal Assistant", "Database Administrator", "Business Development Consultant", "Operations Director", "Director of Digital Marketing", "Communications Director", "Senior Art Director", "VP HR", "Account Representative", "Production Coordinator", "Inside Sales", "Sr. Manager", "Vice President, Sales & Marketing", "Portfolio Manager", "Board member", "Communications Specialist", "Public Relations Manager", "Executive", "Business Development Intern", "Senior Producer", "QA Engineer", "Operations", "Vice President Operations", "Marketing Communications Specialist", "Inside Sales Manager", "Social Media Intern", "Programmer/Analyst", "Communications Intern", "Staff Writer", "Training Manager", "VP, Marketing", "Software Development Engineer", "Manager, Purchasing", "VP Human Resources", "Sr. Systems Engineer", "Program Coordinator", "CEO and Co-Founder", "Campaign Manager", "Director of Accounting", "Staffing Manager", "Market Research Analyst", "Administrator", "EVP, CFO", "Board of Advisors", "Regional Account Manager", "Manager, Finance", "Credit Analyst", "Business Development Associate", "Senior Web Developer", "Engineering Intern", "Financial Consultant", "VP Product Management", "Customer Service", "Advisory Board", "Photographer", "Independent Contractor", "General Sales Manager", "Assistant Brand Manager", "Assistant Director", "Accounting Supervisor", "Professor", "President & COO", "CEO/Founder", "Senior Director, Product Management", "Co-founder & CEO", "General Partner", "Assistant Marketing Manager", "Director of Marketing and Communications", "Director, Communications", "VP, Business Development", "Paralegal", "Senior Business Development Manager", "Technical Writer", "Publisher", "Media Supervisor", "Lead Engineer", "Tour Manager", "Strategy Consultant", "Business Systems Analyst", "Strategic Advisor", "Assistant Professor", "National Sales Director", "Trustee", "Assistant Store Manager", "Social Media Marketing Manager", "Director of Product", "Legal Intern", "Founder / CEO", "President and Founder", "Chairman & CEO", "Field Marketing Manager", "Design Director", "Product Designer", "HR Assistant", "Graduate Student", "Content Manager", "Chief of Staff", "Human Resources Consultant", "Co-Founder & CTO", "Senior Sales Engineer", "Internal Auditor", "Mechanical Engineer", "English Teacher", "Group Product Manager", "Product Director", "Human Resources Specialist", "Technical Support Engineer", "Director, Purchasing", "Head of Business Development", "Director Of Operations", "Technical Account Manager", "Global Account Manager", "Design Intern", "Vice President, Engineering", "HR Specialist", "Tutor", "Entrepreneur in Residence", "Venture Partner", "Senior Director of Marketing", "Social Media Specialist", "Technology Consultant", "Sales Intern", "Digital Strategist", "Co-founder, CEO", "Research Manager", "Senior Solutions Architect", "Software Engineer Intern", "Founder & Chief Executive Officer", "Sales Rep", "Social Media Coordinator", "Product Management", "National Account Executive", "Category Manager", "Marketing Project Manager", "Editorial Assistant", "Plant Controller", "Commercial Director", "Principal Product Manager", "Director of Software Development", "Sales & Marketing Manager", "Chief Commercial Officer", "Recruitment Manager", "Chairman and CEO", "Senior VP & Chief Financial Officer", "Graphic Design Intern", "Email Marketing Manager", "Director, Sales Operations", "DevOps Engineer", "System Analyst", "Content Marketing Manager", "Assistant General Manager", "Principal Architect", "Associate Attorney", "VP Sales & Marketing", "Assistant Buyer", "Manager, Marketing", "Director, Financial Planning & Analysis", "Process Engineer", "Head of Product", "Captain", "Director of Purchasing", "Director of Sales Operations", "CPA", "Service Manager", "Blogger", "Senior Buyer", "Executive Assistant to CEO", "Product Line Manager", "Marketing Operations Manager", "IT Specialist", "Finance Intern", "Finance", "Freelance Designer", "Staff Engineer", "Channel Marketing Manager", "Vice President, Product Development", "President & Chief Operating Officer", "Angel Investor", "Group Account Director", "Sr. Product Marketing Manager", "VP of Business Development", "Scientist", "Resident Assistant", "Senior Systems Analyst", "Senior Systems Administrator", "Freelance Graphic Designer", "Associate General Counsel", "Senior Account Director", "Manufacturing Engineer", "Associate Editor", "Senior Editor", "Talent Acquisition Specialist", "Cashier", "Manager, Business Development", "Operations Analyst", "Regional Marketing Manager", "Bartender", "Executive VP & Chief Financial Officer", "Systems Architect", "Marketing Programs Manager", "Co-founder and CEO", "Chief Innovation Officer", "Marketing Representative", "Enterprise Account Manager", "Trainer", "Senior Scientist", "Board Advisor", "VP, Human Resources", "Graduate Teaching Assistant", "President and Chief Executive Officer", "Credit Manager", "SVP, CFO", "Student Assistant", "Research Engineer", "Communications Coordinator", "Staffing Consultant", "Event Planner", "Senior Architect", "Barista", "Entrepreneur", "Head of Sales", "QA Manager", "Vice President & Chief Financial Officer", "Senior Graphic Designer", "CEO, Founder", "Market Manager", "Media Director", "Freelancer", "Senior Copywriter", "Division Controller", "Sr. Vice President", "Managing Member", "Sr Software Engineer", "Coach", "Director, Digital Marketing", "Board Of Directors", "Office Administrator", "President & Founder", "Technical Support", "Chief People Officer", "Chief Medical Officer", "Sr. Business Analyst", "Technical Product Manager", "Product Owner", "Development Director", "Executive Creative Director", "Sales Development Manager", "Teller", "Co Owner", "Product Engineer", "Product Marketing", "Staff Software Engineer", "Software Engineering Manager", "Loan Officer", "Director, Engineering", "President / CEO", "Production Intern", "Assistant Treasurer", "Social Media Strategist", "Director of Public Relations", "Vice President Sales and Marketing", "Network Manager", "Director, Marketing & Communications", "Director of Software Engineering", "Senior Programmer", "Senior Finance Manager", "Retired", "Co-Founder, CEO", "Agent", "Chief Executive", "Human Resources Representative", "Benefits Manager", "Application Engineer", "Business Intelligence Analyst", "President and COO", "Applications Engineer", "HR", "Director of Recruiting", "Digital Marketing Intern", "President/Owner", "Data Architect", "Manager, Product Development", "Manager, Product Marketing", "Sales Account Manager", "Senior Partner", "CEO, Co-founder", "Senior Software Architect", "Associate Partner", "Assistant Editor", "Research Fellow", "AVP", "Coordinator", "VP IT", "Supply Chain Manager", "Speaker", "CEO & President", "Assistant General Counsel", "Technician", "Research Director", "Specialist", "Director, Client Services", "Java Developer", "Investment Analyst", "Chief Executive Officer & President", "Advertising Manager", "Marketing Strategist", "President, COO", "Information Technology Manager", "Quality Manager", "Director of Marketing Communications", "Quality Assurance Manager", "Personal Banker", "Co-Founder and CTO"]

export const States = {
        'AL': 'Alabama',
        'AK': 'Alaska',
        'AS': 'America Samoa',
        'AZ': 'Arizona',
        'AR': 'Arkansas',
        'CA': 'California',
        'CO': 'Colorado',
        'CT': 'Connecticut',
        'DE': 'Delaware',
        'DC': 'District of Columbia',
        'FM': 'Federated States Of Micronesia',
        'FL': 'Florida',
        'GA': 'Georgia',
        'GU': 'Guam',
        'HI': 'Hawaii',
        'ID': 'Idaho',
        'IL': 'Illinois',
        'IN': 'Indiana',
        'IA': 'Iowa',
        'KS': 'Kansas',
        'KY': 'Kentucky',
        'LA': 'Louisiana',
        'ME': 'Maine',
        'MH': 'Marshall Islands',
        'MD': 'Maryland',
        'MA': 'Massachusetts',
        'MI': 'Michigan',
        'MN': 'Minnesota',
        'MS': 'Mississippi',
        'MO': 'Missouri',
        'MT': 'Montana',
        'NE': 'Nebraska',
        'NV': 'Nevada',
        'NH': 'New Hampshire',
        'NJ': 'New Jersey',
        'NM': 'New Mexico',
        'NY': 'New York',
        'NC': 'North Carolina',
        'ND': 'North Dakota',
        'OH': 'Ohio',
        'OK': 'Oklahoma',
        'OR': 'Oregon',
        'PW': 'Palau',
        'PA': 'Pennsylvania',
        'PR': 'Puerto Rico',
        'RI': 'Rhode Island',
        'SC': 'South Carolina',
        'SD': 'South Dakota',
        'TN': 'Tennessee',
        'TX': 'Texas',
        'UT': 'Utah',
        'VT': 'Vermont',
        'VI': 'Virgin Island',
        'VA': 'Virginia',
        'WA': 'Washington',
        'WV': 'West Virginia',
        'WI': 'Wisconsin',
        'WY': 'Wyoming'
      }

export const DataPointTypes = [
          "Address",
          "AlexaGlobalRank",
          "AlexaUsRank",
          "Avatar",
          "Bio",
          "BlogUrl",
          "BusinessModel",
          "ChattingWith",
          "CompanyLinkedinUrl",
          "CompanyName",
          "CrunchbaseHandle",
          "Description",
          "Domain",
          "Education",
          "Email",
          "EmailDomain",
          "EmployeeCountRange",
          "EmployeeGrowth",
          "ExperiencedIn",
          "FacebookHandle",
          "FamilyName",
          "FoundedBy",
          "FullName",
          "Gender",
          "GithubHandle",
          "GivenName",
          "GoogleRank",
          "HasADegreeIn",
          "HaveRaised",
          "HaveRaisedRange",
          "Industry",
          "InfluentialAbout",
          "Is",
          "Knows",
          "LegalName",
          "Like",
          "LinkedinUrl",
          "Location",
          "LocationGeneral",
          "MarketCap",
          "MemberOfTheGroup",
          "MentionedInNews",
          "NumberOfEmployees",
          "OfficeInCity",
          "OfficeInCountry",
          "OfficeInRegion",
          "OfficeInState",
          "OfficePhone",
          "Ownership",
          "Phone",
          "Position",
          "PreviousCompany",
          "PreviousTitle",
          "ReportsToName",
          "Revenue",
          "RevenueRange",
          "SalesGrowth",
          "Sector",
          "Seniority",
          "SfdcCustomValue",
          "Studied",
          "Tag",
          "TalkingAbout",
          "Tech",
          "Ticker",
          "TimeZone",
          "Title",
          "TwitterHandle",
          "UsesApp",
          "UsesService",
          "UtcOffset",
          "Wants",
          "WantsLocation",
          "Website",
          "WorkedInDepartment",
          "WorksAt",
          "WorksInDepartment",
          "WorksWith",
          "WroteAnArticle",
        ];

export const FACTS = [
  {
    "value": "addresses.state",
    "label": "State"
  },
  {
    "value": "number_of_employees",
    "label": "Number of Employees"
  }
]